### ISSUE TITLE
Select port over command line

### ISSUE THREAD

**Issue by spacehuhn** [SpacehuhnTech/Huhnitor#12]
Would be very convinient to chose the serial port over the command line directly like
`huhnitor -p COM3`

**Comment by xkey10x** [comment]
When first initiating Huhnitor, the prompt shows available serial ports
[]()![image](https://user-images.githubusercontent.com/57377849/141668338-81909701-1921-43f8-9391-d0699034496b.jpeg)

**Comment by the-Jamz** [comment]
@xkey10x Hi, is a support request and doesn't belong here, please check out the discord server and ask for help there if you need it.

**Comment by the-Jamz** [comment]
Implemented in PR #21
