### ISSUE TITLE
Auto exit after 3 CTRL+C in a row

### ISSUE THREAD

**Issue by spacehuhn** [SpacehuhnTech/Huhnitor#15]
Automatically close the huhnitor if the user presses CTRL+C (and only that) 3 times in a row. 
Thtat way it's more idiot safe but also convinient.

**Comment by the-Jamz** [comment]
How do you feel about keeping the exit command, just so we don't need to rely on saying spam ctrl + c to close the program?

**Comment by spacehuhn** [comment]
Yes the exit command stays available, this is just a addon feature.

**Comment by spacehuhn** [comment]
Another additional way to exit could be `q`. I'm getting used to use `q` to exit from other terminal applications because it's annoying to type out `exit` all the time.
