### ISSUE TITLE
"huhn read" not working whith ;;

### ISSUE THREAD

**Issue by m00nbyt3** [SpacehuhnTech/Huhnitor#18]
While concatenating  two commands with `;;` sequence, the `huhn read` command isnt working.

**Comment by spacehuhn** [comment]
Can you provide us with an example to reproduce the behaviour?

**Comment by m00nbyt3** [comment]
![huhn](https://user-images.githubusercontent.com/34653601/93767541-77f23c80-fc18-11ea-8490-377a2e0a372b.PNG)

**Comment by spacehuhn** [comment]
Thank you. This is intended behaviour. `huhn` is a command used by huhnitor (so it runs locally on your computer) and can't be interpreted by the ESP8266 Deauther. In your case, I'd suggest you move your command `help -s` inside your file `help.txt`.
