### ISSUE TITLE
little issue with "start" montage  order

### ISSUE THREAD

**Issue by vexxrs** [SpacehuhnTech/Huhnitor#19]
![start_montage_issue](https://user-images.githubusercontent.com/1551539/97218005-d2962f80-17a6-11eb-9a1b-689af79b60d3.png)

Once you use "start" and try an "alias" 
Following "start" steps lead to incorrect order of parameters

Just switching the order of "-name xxxx" "-mac xx:xxx:xxxxxx" solve it

_Sory for bady engilish~_

**Comment by the-Jamz** [comment]
Which deauther version are you using, so I can try to replicate the issue?

**Comment by spacehuhn** [comment]
Thank you for reporting! This is a deauther bug so not on the huhnitor side of things - but doesn't matter I just pushed a fix :)
