### ISSUE TITLE
Better serial port picker

### ISSUE THREAD

**Issue by spacehuhn** [SpacehuhnTech/Huhnitor#2]
This is how I imagine it:  

0. Application starts
1. Lists all available ports (line by line) with some sort if ID/numerbing
2. User either types in the port name, the ID/number or plugs in a new device
3. When a new serial device was detected or the manual port selection was successful, print the connected message and continue the program.

A parameter, maybe `--no-auto` disables to auto connect feature. So that if a new port was detected, it just gets added/printed to the previous port selection list.

**Comment by the-Jamz** [comment]
That parameter does seem more intuitive compared to `-s`, and yes detecting new devices plugged in while in the `--no-auto` mode does sound good, but as far as numbing the ports goes: I wanted to leave it a little bit more open (eg. user is able to type in any path they like) in case a port isn't detected by Huhnitor for some reason.

**Comment by spacehuhn** [comment]
> but as far as numbing the ports goes: I wanted to leave it a little bit more open (eg. user is able to type in any path they like) in case a port isn't detected by Huhnitor for some reason.

I'd say we can do both like

```
[0] /dev/ttyUSB0
[1] /dev/ttyS3
```

typing `/dev/ttyUSB0` would work just like `0`.
Making it as easy as possible for the user.

I guess we'd have to think of a way to distinguish user input between the number and a real serial port.

**Comment by the-Jamz** [comment]
Yeah a sort of hybrid sounds perfect.
