### ISSUE TITLE
Error upon plugging in device

### ISSUE THREAD

**Issue by skouv05** [SpacehuhnTech/Huhnitor#31]
Hey. When i plug in my board i get this error
<img width="540" alt="Capture" src="https://user-images.githubusercontent.com/107479268/200004095-211e224a-f457-4c58-a2b2-6f0ef66cea5b.PNG">

**Comment by the-Jamz** [comment]
@spacehuhn I did a little digging here and it seems like it may be from the deauther side, any pointers?

**Comment by skouv05** [comment]
Im really dumb. I forgot to upload the deauth code to the board. My bad

**Comment by the-Jamz** [comment]
> Im really dumb. I forgot to upload the deauth code to the board. My bad

Happens to the best of us :)
