### ISSUE TITLE
Goodbye message

### ISSUE THREAD

**Issue by spacehuhn** [SpacehuhnTech/Huhnitor#7]
Not sure if and how possible, but instead of CTRL+C resulting in 
```
error: process didn't exit successfully: `target\debug\huhnitor.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```
we should think about a proper goodbye message. Maybe also a proper way to exit without CTRL+C.

**Comment by spacehuhn** [comment]
Seems like that error only appears when using `cargo run` and not when starting the compiled executable. 
Though a goodbye message would be nice anyway, even if you wouldn't see it when you close the entire terminal.
But then again, if no error, no problem. This is probably the most unnecessary feature request yet.

**Comment by the-Jamz** [comment]
Should be simple enough to add though

**Comment by the-Jamz** [comment]
This has since been added @spacehuhn yes?

**Comment by spacehuhn** [comment]
With our current implementation of capturing CTRL+C and `exit`, I don't think there's a need for my original idea anymore.
