### ISSUE TITLE
Absolute noob here - how do I run the downloaded release?

### ISSUE THREAD

**Issue by robin-weaver** [SpacehuhnTech/Huhnitor#8]
Please forgive the ignorance.

**Comment by the-Jamz** [comment]
No worries- on Windows or (I presume) Mac, if you don't need to enter any arguments, just running it as you would a normal program should work fine. If you need manual mode, or if you're having trouble, CDing into the folder containing the executable and entering the full name 
(including .exe on Windows) followed by any arguments will run it. 

On Linux, CDing into the directory containing the executable then running `./[name]` eg `./huhnitor_1.0.1_linux` will run it.

If you're on Mac, please note we currently can't test for this platform, but we should be able to soon.

**Comment by robin-weaver** [comment]
Okay, turns out I'm not as bad as thought, that's what I was doing but I'm getting this error:
`-bash: ./huhnitor_1.0.1_linux: cannot execute binary file: Exec format error
`

Any thoughts? Running this on a Pi on raspbian lite.

Edit: Only having this issue on the pi. It launches perfectly on my debian based VM.

**Comment by the-Jamz** [comment]
Yes, appears that Raspbian is not supported on our pre-compiled Linux release. If you would like to run it on there, check the README for instructions on how to compile it on the Pi. (This would allow you to run it on there). You can download the code at the time of the release on the releases page, next to the executables. If you're feeling brave, you could try the code from master.

**Comment by robin-weaver** [comment]
Thanks! I'll see how I get on.

**Comment by spacehuhn** [comment]
Maybe we can setup a raspi to compile a binary for our releases too 🤔

**Comment by robin-weaver** [comment]
@spacehuhn If you don't have one or access to one I'd be happy to help :)

**Comment by spacehuhn** [comment]
Yes you can help by trying to compile and run it on your pi and give us feedback :)

**Comment by robin-weaver** [comment]
Hey just tried this on a fresh upgraded install of raspbian lite, got the following error while compiling after following the readme compiling instructions:

```
`error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/pi/Huhnitor/target/release/build/libudev-sys-0ca2f787a064fa72/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libudev\' found\n"', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed`
```

Should I open a separate issue for this?

**Comment by spacehuhn** [comment]
Sorry for the late reply, it seems like you're missing dependencies, try running `sudo apt install libudev-dev pkg-config`. 
Also, just setup snap support yesterday `sudo snap install huhnitor --edge --devmode` - check out the [README](https://github.com/SpacehuhnTech/Huhnitor#using-snap-recommended-for-linux)

**Comment by robin-weaver** [comment]
Installing via snap worked perfectly! All working fine, thanks for the help.
